nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: [ 'https://groupe-3.lycee-stvincent.net', 'http://localhost:5173','http://192.168.55.66:5173' ]
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ 'https://groupe-3.lycee-stvincent.net', 'http://localhost:5173', 'http://192.168.55.66:5173' ]
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            expose_headers: ['Authorization']
            allow_credentials: true
